name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Checkout Wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
          cd ${{ github.repository }}.wiki
          # Populate the Wiki with relevant information
          echo "## Project Updates" >> Home.md
          echo "### New Features" >> Home.md
          git add Home.md
          git commit -m "Update Wiki with new features and changes"
          git push
